spring.application.name=server
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5431/postgres
spring.datasource.username=postgres
spring.datasource.password=password

jwt.secretKey=baufbaiwefaweufeaiufavisbvsdipisdnvaskjvskvpofpowaejrfposdkvnalsdvbafjbkujfewoifjwaajsbdifuauifbvdoivnoiehgoihervbikfbaiub

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true