spring.application.name=business-server
server.port=8081

# H2 Connection
spring.datasource.url=jdbc:h2:mem:stockmanagement;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER;INIT=RUNSCRIPT FROM 'classpath:stockmanagement.sql'
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect